### ISSUE TITLE
Problem with parsing the tree

### ISSUE THREAD

**Issue by mavino** [aschweickart/CompBioSummer2015#7]
This is my newick file:
```
(((p15, (p3, p13) p21) p19, (p4, (((p17, p9) p25, p11)p23, ((p1, p5) p26, ((p10, p2) p28, (p6, ((p16, (p12, p14) p33) p31, (p7, p8) p32) p30) p29) p27) p24) p22) p20)) p34;
((((h1, h2) h21, h3) h19, (h4, ((h5, (h6, (h7, (h8, h9) h32) h28) h25) h23, (((h10, h11) h29, (h12, h13) h30) h26, (h14, (h15, (h16, h17) h33) h31) h27) h24) h22) h20)) h34;
p1:h1
p2:h2
p3:h3
p4:h4
p5:h5
p6:h6
p7:h7
p8:h8
p9:h9
p10:h10
p11:h11
p12:h12
p13:h13
p14:h14
p15:h15
p16:h16
p17:h17
```
I am loading it in costscape.py and I am having the following error:
```
Costscape 0.0.5
Enter .newick input file name: /home/marianoavino/Downloads/xscape/examples/example.newick
Traceback (most recent call last):
  File "./costscape", line 47, in <module>
    if __name__ == '__main__': main()
  File "./costscape", line 26, in main
    getInput.getInput(outputExtension = "pdf", allowEmptyOutfile=True)
  File "/home/marianoavino/Downloads/xscape/bin/xscape/getInput.py", line 24, in getInput
    hostTree, parasiteTree, phi = newickFormatReader(fileHandle)
  File "/home/marianoavino/Downloads/xscape/bin/xscape/newickFormatReader.py", line 47, in newickFormatReader
    hostDict = parseNewick(hostString, "host")
  File "/home/marianoavino/Downloads/xscape/bin/xscape/newickFormatReader.py", line 69, in parseNewick
    buildTreeDictionary(buildTree(dfsList), "Top", treeDict, treeType)
  File "/home/marianoavino/Downloads/xscape/bin/xscape/newickFormatReader.py", line 91, in buildTree
    leftTree = buildTree(leftList)
  File "/home/marianoavino/Downloads/xscape/bin/xscape/newickFormatReader.py", line 82, in buildTree
    rootName = dfsList[0][0]
IndexError: list index out of range

**Comment by mavino** [comment]
this is obviously related to the way your script 'newickFormatReader.py' handles the root of my tree...
indeed my 'leftList' is an empty list and that is why when it tries to make 'leftTree = buildTree(leftList)', it raises 'IndexError: list index out of range'...
But I don't see anything strange related to my root if comapred to the trees you have as an example (gopher_louse.newick)...

**Comment by mavino** [comment]
This what happens to my parasite tree when I open it in Bio.Phylo
```
>>> tree = Tree('(((p15, (p3, p13) p21) p19, (p4, (((p17, p9) p25, p11)p23, ((p1, p5) p26, ((p10, p2) p28, (p6, ((p16, (p12, p14) p33) p31, (p7, p8) p32) p30) p29) p27) p24) p22) p20)) p34;',format=8)
>>> print tree.get_ascii(show_internal=True)

         /-p15
      /p19
     |  |   /-p3
     |   \p21
     |      \-p13
-p34-|
     |   /-p4
     |  |
     |  |         /-p17
     |  |      /p25
      \p20  /p23  \-p9
        |  |  |
        |  |   \-p11
        |  |
         \p22     /-p1
           |   /p26
           |  |   \-p5
           |  |
            \p24     /-p10
              |   /p28
              |  |   \-p2
              |  |
               \p27  /-p6
                 |  |
                 |  |      /-p16
                  \p29  /p31
                    |  |  |   /-p12
                    |  |   \p33
                     \p30     \-p14
                       |
                       |   /-p7
                        \p32
                           \-p8
```
Notice the position of root P34.
While if I use your example parasite tree (form gopher_louse.newick)
```
tree = Tree('((p18, p19) p4, ((p22, (p24, p25) p23) p20, (p26, ((p30, p31) p28, (p32, p33) p29) p27) p21) p5) p3;',format=8)
>>> print tree.get_ascii(show_internal=True)

      /-p18
   /p4
  |   \-p19
  |
-p3      /-p22
  |   /p20
  |  |  |   /-p24
  |  |   \p23
   \p5      \-p25
     |
     |   /-p26
     |  |
      \p21     /-p30
        |   /p28
        |  |   \-p31
         \p27
           |   /-p32
            \p29
               \-p33
```
Notice now the root p3. It is shown graphically different than my root (p34)...I think this is driving the problem..Any idea on how I can fix this? Is it my newick file malformed, and if yes how do I fix it?
Moreover if I opened my parasite tree in Archaeopteryx v.09928 beta I get the warning;
```
Warning: Possible Error in New Hampshire Formatted Data
One or more trees contain (a) node(s) with one discendant, possibly indicating illeagal parentheses within node names
```
However, I will be able to see the tree.
When I open your tree it does not fire the same warning.
